import {Montserrat} from "next/font/google";
import "./globals.css";
import {cn} from "@/lib/utils";
import 'react-toastify/dist/ReactToastify.css'
import {Header} from "@/components/widgets/header";
import NextTopLoader from "nextjs-toploader";
import {Slide, ToastContainer} from "react-toastify";
import {ThemeProvider} from "@/components/shared/theme-provider";
import {StoreProvider} from "@/components/entities/store";

const inter = Montserrat({subsets: ["latin"]});

export const metadata = {
    title: "Lichi Dashboard",
    description: "Generated by create next app",
};

export default function RootLayout({children}) {
    return (
        <StoreProvider>
            <html lang="en" suppressHydrationWarning>
            <body
                className={cn(
                    "min-h-screen bg-background antialiased",
                    inter.className
                )}
                translate={"no"}
            >
            <NextTopLoader
                color="#000"
                showSpinner={false}
                zIndex={10010}
            />
            <ToastContainer
                position={'top-right'}
                autoClose={3000}
                hideProgressBar={true}
                newestOnTop={false}
                closeOnClick={false}
                rtl={false}
                pauseOnFocusLoss={false}
                draggable={false}
                pauseOnHover={false}
                className="toast-container"
                theme={"colored"}
                transition={Slide}
            />
            <ThemeProvider
                attribute="class"
                defaultTheme="system"
                enableSystem
                disableTransitionOnChange
            >
                <Header/>
                <main>
                    {children}
                </main>
            </ThemeProvider>
            </body>
            </html>
        </StoreProvider>
    );
}
